service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  getProductsList:
    handler: handlers.getProductsList
    events:
      - http:
          method: get
          path: books
          cors: true
  getProductById:
    handler: handlers.getProductById
    events:
      - http:
          method: get
          path: book/{bookId}
          cors: true
