service:
  name: testa
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  first:
    handler: first.hello
    events:
      - http:
          path: books
          method: get
          cors: true
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
