service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    PG_HOST: aws-node-db-instance.csgvm17alrq7.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: fake-db-name
    PG_USERNAME: postgres
    PG_PASSWORD: fakePassword
    SQS_URL:
      Ref: SQSQueue

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "catalogItemsQueue"
  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
    SQSQueueArn:
      Value:
        Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  invokeDb:
    handler: handlers.invokeDb
  getProductsList:
    handler: handlers.getProductsList
    events:
      - http:
          method: get
          path: books
          cors: true
  getProductById:
    handler: handlers.getProductById
    events:
      - http:
          method: get
          path: book/{bookId}
          cors: true
  postProduct:
    handler: handlers.postProduct
    events:
      - http:
          method: post
          path: book
          cors: true
  catalogBatchProcess:
    handler: handlers.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
