service:
  name: authorization-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

resources:
  Resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt: [ BasicAuthorizerLambdaFunction, Arn ]

functions:
  basicAuthorizer:
    handler: handlers.basicAuthorizer
