service:
  name: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    SQS_URL: "${cf:product-service-${self:provider.stage}.SQSQueueUrl}"
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::ea-import-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::ea-import-service/*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - "${cf:product-service-${self:provider.stage}.SQSQueueArn}"

functions:
  importProductsFile:
    handler: handlers.importProductsFile
    events:
      - http:
          method: get
          path: import
          cors: true
          authorizer:
            name: tokenAuthorizer
            arn: '${cf:authorization-service-${self:provider.stage}.basicAuthorizerArn}'
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
            type: token
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handlers.importFileParser
    events:
      - s3:
          bucket: ea-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    GatewayResponseAccessDenied:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ResponseType: ACCESS_DENIED
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
    GatewayResponseUnauthorized:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ResponseType: UNAUTHORIZED
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"